config/routes.rb
Cr2::Application.routes.draw do

  resources :preinscriptions

  resources :sections

  get "home/index"

  resources :pensums

  resources :subjects

  resources :magisters

  resources :folders


  # The priority is based upon ordeoppan gangnam styler of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
    # match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
 root :to => 'home#index'
  resources :sections do
    collection do
      post :try
    end
  end

  resources :folders do
    collection do
      post :add
    end
  end

  resources :folders do
    collection do
      post :increase
    end
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/preinscription.rb
class Preinscription < ActiveRecord::Base
  attr_accessible :enrolled, :pensum_id, :subject_id, :date
  belongs_to :subject
  belongs_to :pensum

  #Validar todos los campos requeridos
  validates :enrolled, :pensum_id, :subject_id, :presence => {:message => "Todos los campos son requeridos" }

end

app/controllers/preinscriptions_controller.rb
class PreinscriptionsController < ApplicationController
  # GET /preinscriptions
  # GET /preinscriptions.json
  def index
    @preinscriptions = Preinscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @preinscriptions }
    end
  end

  # GET /preinscriptions/1
  # GET /preinscriptions/1.json
  def show
    @pensum = Pensum.find(params[:id])
    @preinscriptions = @pensum.preinscriptions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @preinscriptions }
    end
  end

  # GET /preinscriptions/new
  # GET /preinscriptions/new.json
  def new
    @preinscription = Preinscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @preinscription }
    end
  end

  # GET /preinscriptions/1/edit
  def edit
    @preinscription = Preinscription.find(params[:id])
  end

  # POST /preinscriptions
  # POST /preinscriptions.json
  def create
    @preinscription = Preinscription.new(params[:preinscription])

    respond_to do |format|
      if @preinscription.save
        format.html { redirect_to @preinscription, notice: 'Preinscription was successfully created.' }
        format.json { render json: @preinscription, status: :created, location: @preinscription }
      else
        format.html { render action: "new" }
        format.json { render json: @preinscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /preinscriptions/1
  # PUT /preinscriptions/1.json
  def update
    @preinscription = Preinscription.find(params[:id])

    respond_to do |format|
      if @preinscription.update_attributes(params[:preinscription])
        format.html { redirect_to @preinscription, notice: 'Preinscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @preinscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preinscriptions/1
  # DELETE /preinscriptions/1.json
  def destroy
    @preinscription = Preinscription.find(params[:id])
    @preinscription.destroy

    respond_to do |format|
      format.html { redirect_to preinscriptions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/preinscriptions_helper.rb
module PreinscriptionsHelper
end

app/views/preinscriptions/_form.html.erb
<%= form_for @preinscription, :url => {:action => :show, :id => @preinscription.pensum_id} do |f| %>
  <% if @preinscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preinscription.errors.count, "error") %> prohibited this preinscription from being saved:</h2>

      <ul>
      <% @preinscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :enrolled %><br />
    <%= f.number_field :enrolled %>
  </div>
  <%= hidden_field_tag(:subject_id, @preinscription.subject_id)%>
  <%= hidden_field_tag(:pensum_id, @preinscription.pensum_id)%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preinscriptions/edit.html.erb
<h1>Editing preinscription for subject <%=Subject.find(@preinscription.subject_id).name%> </h1>

<%= render 'form' %>

<%= link_to 'Back', :action => :show,:id => @preinscription.pensum_id %>

app/views/preinscriptions/index.html.erb
<h1>Listing preinscriptions</h1>

<table>
  <tr>
    <th>Subjectname</th>
    <th>Enrolled</th>
    <th>Pensum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<%@m = Date.current().month %>

<%if @m <= 6 %>
<%@date = Date.current().year.to_s + '-1' %>
<%else %>
<%@date = Date.current().year.to_s + '-2' %>
<%end %>

<% for j in @preinscriptions%>
<% if j.date != @date%>
<%   Preinscriptions.delete(j) %>
<% end %> 

<% @preinscriptions.each do |preinscription| %>
  <tr>
    <td><%= Subject.find(preinscription.subject_id).name %></td>
    <td><%= preinscription.enrolled %></td>
    <td><%= preinscription.pensum_id %></td>
    <td><%= link_to 'Show', preinscription %></td>
    <td><%= link_to 'Edit', edit_preinscription_path(preinscription) %></td>
    <td><%= link_to 'Destroy', preinscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Preinscription', new_preinscription_path %>

<br>
-----------------------------------------------------------------------------------------------
<p id="notice"><%= notice %></p>

<h2>Select a pensum</h2>
   <table>

<table>
  <tr>
    <th>Magister</th>
    <th>Start year (Semestre)</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

 <% for pensum in Pensum.all %>
  <tr>
    <td><%= Magister.find(pensum.magister_id).code %></td>
    <td><%= pensum.year %>(<%= pensum.semester %>)</td>
    <td><%= link_to 'Show Preinscription', :action => :show, :id => pensum.id %></td>    
  </tr>
<% end %>
</table>

<br />
<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"), "http://localhost:3000/" )%>

app/views/preinscriptions/new.html.erb
<h1>Preinscription</h1>
  
<table>
  <%= form_tag(add_preinscription_path) %>
  <% for subj in @folder.subjects %>
  <% preins = Preinscription.where(:subject_id => subj.id).first %>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Credits</th>   
      <th>Capacity</th>    
      <th>Number of blocks</th>
      <th>Enrolled</th>
    </tr>
    <tr>
      <td><%= subj.code %></td>
      <td><%= subj.name %></td>
      <td><%= subj.credits %></td>
      <td><%= subj.capacity %></td>
      <td><%= subj.blocks %></td>
      <td><%= preins.enrolled %></td>
      <td><%= check_box_tag "media_ids[]", m.id  %> </td>
    </tr>     
  <% end %>  
</table>

<%= submit_tag "Save", class:"btn btn-primary" %>

<%= link_to 'Back', @folder %>

app/views/preinscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<%if params[:id]==nil %>
<h1>There are no preinscriptions</h1>
<% end %>

<%if params[:id]!=nil %>
<h2>Subject Preinscriptions</h2>
   <table>
    <tr>
      <th>Subject Name</th>
      <th>Enrolled</th>    
    </tr>
   <% total=0 %>

<% for preinscription in Preinscription.where(:pensum_id=>params[:id]) %>
    
      <% total=total+preinscription.enrolled %>
  <% end %>

 <% for preinscription in Preinscription.where(:pensum_id=>params[:id]) %>
    <tr>
      <td><%= Subject.find(preinscription.subject_id).name %></td>
      <td><%= preinscription.enrolled %>/<%=Subject.find(preinscription.subject_id).capacity%></td>
      <td><%= link_to 'Edit', edit_preinscription_path(preinscription) %></td>
    </tr>
  <% end %>
</table>
  <% end %>

<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"), "http://localhost:3000/subjects/new?id="+params[:id] )%>