config/routes.rb
Cr2::Application.routes.draw do

  resources :preinscriptions

  resources :sections

  get "home/index"

  resources :pensums

  resources :subjects

  resources :magisters

  resources :folders


  # The priority is based upon ordeoppan gangnam styler of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
    # match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
 root :to => 'home#index'
  resources :sections do
    collection do
      post :try
    end
  end

  resources :folders do
    collection do
      post :add
    end
  end

  resources :folders do
    collection do
      post :increase
    end
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :code, :docid, :name, :semester, :year, :pensum_id, :magisterName, :preinscription_date
 # has_many :subjects
#  has_one :pensum

  has_and_belongs_to_many :subjects

#Validar todos los campos requeridos
  validates :year, :code, :docid, :name, :semester, :presence => { :message => "Todos los campos son requeridos" }
  
  #Validar asociaciones -> No validar del otro lado (eg de materium a carpetum)
  validates_associated :subjects
#  validates_associated :pensum
  
  #Validar tamaño y tipos
  validates :year, :length => { :is => 4 }
  validates :year, :numericality => { :only_integer => true }
  validates :year, :numericality => { :greater_than => 1970 }
  validates :code, :length => { :is => 9 }
  validates :code, :numericality => { :only_integer => true }
  validates :code, :uniqueness => true
  validates :docid, :numericality => { :only_integer => true }
  validates :docid, :uniqueness => true
  validates :name, :format => { :with => /\A[a-zA-Z\s]+\z/ }
  validates :semester, :length => { :is => 1 }
  validates :semester, :numericality => { :only_integer => true }
  validates :semester, :numericality => { :greater_than_or_equal_to => 0 }
  validates :semester, :numericality => { :less_than_or_equal_to => 2 }

 

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  # GET /folders
  # GET /folders.json
  def index
    @folders = Folder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @folders }
    end
  end

  def add
    @folder = Folder.find(params[:id])
    mat = params[:mat]
    @subject = Subject.where(:name => mat).first

    if(@folder.subjects.where(:id => @subject.id).size == 0)
      @folder.subjects << @subject
    end

    respond_to do |format|
      format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
      format.json { render json: @folder }
    end
  end 

  # GET /folders/1
  # GET /folders/1.json
  def show
    @folder = Folder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @folder }
    end
  end

  # GET /folders/new
  # GET /folders/new.json
  def new
    @folder = Folder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @folder }
    end
  end

  # GET /folders/1/edit
  def edit
    @folder = Folder.find(params[:id])
  end

  # POST /folders
  # POST /folders.json
  def create
    #@magisterF = Magister.find_by_code(params[:folder][:magisterName])

    #Search for the active pensum for that magister
    @pensumF = Pensum.where(:magister_id => params[:folder][:magisterName]).first
    #If the pensum exist create the folder with the pensum id for the magister
    if @pensumF != nil
      @folder = Folder.new(params[:folder].merge(:pensum_id => @pensumF.id))
    
     respond_to do |format|
        if @folder.save
          format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
          format.json { render json: @folder, status: :created, location: @folder }
        else
        format.html { render action: "new" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
        end
      end
      #if the pensum doesnt exist redirects to the metod errorMaestria
    else respond_to do |format|
        format.html { render action: "errorMaestria" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /folders/1
  # PUT /folders/1.json
  def update
    @folder = Folder.find(params[:id])

    respond_to do |format|
    if @folder.update_attributes(params[:folder])
      format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
      format.json { head :no_content }
    else
      format.html { render action: "edit" }
      format.json { render json: @folder.errors, status: :unprocessable_entity }
    end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy

    respond_to do |format|
      format.html { redirect_to folders_url }
      format.json { head :no_content }
    end
  end
  
  #Metod that redirects to the view page of the error "errorMaetria"
  def errorMaestria
    respond_to do |format|
      format.html  errorMaestria.html.erb
    end
  end

  # Metod that recives the data from the prenscription
  def increase
    @folder = Folder.find(params[:id])

    subjectsId = Subject.find(params[:subj_ids])

    @m = Date.current().month

    if @m <= 6
    @date = Date.current().year.to_s + '-1'
    else
    @date = Date.current().year.to_s + '-2'
    end
  
    @folder.update_attributes(:preinscription_date => @date)

    subjectsId.each do |s|
      @Preinscription = Preinscription.where(:subject_id => s.code).first
      numNuevo = @Preinscription.enrolled + 1
      @Preinscription.update_attributes(:enrolled => numNuevo)
    end

    respond_to do |format|
      format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
      format.json { render json: @folder }
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper


end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Student name<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    ID number<br />
    <%= f.number_field :docid %>
  </div>
  <div class="field">
    Code<br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    Year in<br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    Semester<br />
    <%= f.text_field :semester %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>  
  <%= hidden_field_tag(:sub, "0")%>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render 'form' %>

<% @folder = Folder.find(params[:id]) %>
<% @subjectsNotSeen = Pensum.find(@folder.pensum_id).subjects %>

<% for j in @folder.subjects %>
<%   @subjectsNotSeen.delete(j) %>
<% end %> 

<h2>Select Seen Subjects</h2>
<%= form_tag add_folders_path, :url => {:action => :add, :sub => "1"} do %>
<br><select name="mat">
  <% for sub in @subjectsNotSeen do %>
    <option><%=sub.name%></option>
  <% end %>
  </select><br>

  <%= hidden_field_tag(:id, params[:id])%>
  <%= submit_tag 'Add the subject', class:"btn btn-primary"%>
<% end %>

<% if @folder.preinscription_date == nil  %>
<div class="prueba"> 
<h1>Preinscription</h1>
  
<table>
  <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Credits</th>   
      <th>Capacity</th>    
      <th>Number of blocks</th>
      <th>Enrolled</th>
    </tr>
    
  <%= form_tag increase_folders_path do %>
  <% for subj in @subjectsNotSeen %>
    <% preins = Preinscription.where(:subject_id => subj.code).first %>
    
    <tr>
      <td><%= subj.code %></td>
      <td><%= subj.name %></td>
      <td><%= subj.credits %></td>
      <td><%= subj.capacity %></td>
      <td><%= subj.blocks %></td>

      <td>
        <% if preins.nil? %>
        <%= '0' %>
        <%else%>
        <%= preins.enrolled %>
        <%end%>
      </td>

      <td><%= check_box_tag "subj_ids[]", subj.id  %> </td>

     <%= hidden_field_tag(:id, params[:id])%>
    </tr>     
  <% end %> 

</table>

<%= submit_tag "I'm ready", class:"btn btn-primary" %>
</div>
<% end %>


<div class="actions">
   <%= link_to 'Show', @folder %> |
   <%= link_to "back", folders_path  %>
</div>
<% end %>

app/views/folders/errorMaestria.html.erb
<h1>Error!</h1>
<p>There is not an active pensum for that magister yet!, you need to create it first.</p>

<%= link_to 'Go to Pensums', pensums_path %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<h1>Student folders</h1>

<table>
  <tr>
    <th>Code</th>
    <th>ID Number</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>


<% @folders.each do |folder| %>
  <tr>
    <td><%= folder.code %></td>
    <td><%= folder.docid %></td>
    <td><%= folder.name %></td>
    <td><%= link_to 'Show', folder %></td>
    <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
    <td><%= link_to 'Delete', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'New Folder', new_folder_path %> |
<a href="http://localhost:3000">Back</a> 

app/views/folders/new.html.erb
<h1>New folder </h1>

<%= form_for @folder, :url => {:action => :create, :id => '1'} do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :docid %><br />
    <%= f.number_field :docid %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :semester %><br />
    <%= f.text_field :semester %>
  </div>


  <div class="field">

    
    <%= f.label :magisterName %><br />
    <%= f.collection_select :magisterName, Magister.all, :id, :code %>
   
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Folder</h1>
<p>
  <b>Name:</b>
  <%= @folder.name %>
</p>
<p>
  <b>Code:</b>
  <%= @folder.code %>
</p>
<p>
  <b>ID:</b>
  <%= @folder.docid %>
</p>
<p>
  <b>Year in:</b>
  <%= @folder.year %>-<%= @folder.semester %>
</p>
<p>
  <b>Pensum:</b>
  <%pen = Pensum.where(:id => @folder.pensum_id).first%>
  <%= link_to Magister.find(pen.magister).code, :controller => :subjects, :action => :new, :id => pen.id %>
</p>


<h2>Subjects</h2>
   <table>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Credits</th>      
    </tr>

  
  <% for subject in Folder.find(params[:id]).subjects %>
    <tr>
      <td><%= subject.code %></td>
      <td><%= subject.name %></td>
      <td><%= subject.credits %></td>
      <td><%= link_to 'Show', subject %></td>
    </tr>
  <% end %>
  </table>



<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"),folders_path )%>