config/routes.rb
Cr2::Application.routes.draw do

  resources :preinscriptions

  resources :sections

  get "home/index"

  resources :pensums

  resources :subjects

  resources :magisters

  resources :folders


  # The priority is based upon ordeoppan gangnam styler of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
    # match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
 root :to => 'home#index'
  resources :sections do
    collection do
      post :try
    end
  end

  resources :folders do
    collection do
      post :add
    end
  end

  resources :folders do
    collection do
      post :increase
    end
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :code, :credits, :name, :capacity, :pensum_id, :blocks

  has_and_belongs_to_many :folders
  has_one :preinscription

  belongs_to :pensum

  #Validar todos los campos requeridos
  validates_associated :preinscription
  validates :code, :credits, :name, :presence => { :message => "Todos los campos son requeridos" }
  
  #Validar tamaño y tipos
  validates :code, :uniqueness => true
  validates :capacity, :numericality => { :only_integer => true }
  validates :credits, :numericality => { :only_integer => true }

  validates :blocks, :numericality => { :only_integer => true }

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @pensum = Pensum.find(params[:id])
    @subject = @pensum.subjects.build 
    
   # user.assign_attributes({ :name => 'Josh', :is_admin => true })
   # @subject = Subject.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
      
     end

  end

  # GET /subjects/1/edit
  def edit

    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @pensum = Pensum.find(params[:id])
    @subject = @pensum.subjects.build(params[:subject])    

    @subject.save
    ss=@subject.code
     @m = Date.current().month
    if @m <= 6
    @date = Date.current().year.to_s + '-1'
    else
    @date = Date.current().year.to_s + '-2'
    end
    
   @Preinscription = Preinscription.create(subject_id: @subject.code, enrolled: 0, pensum_id: @pensum.id, date: @date)
    
      redirect_to new_subject_path(:id => @pensum.id)
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for @subject do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :credits %><br />
    <%= f.text_field :credits %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.text_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :blocks %><br />
    <%= f.text_field :blocks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"),pensums_path %>

app/views/subjects/error.html.erb
ERROR
(<%= link_to "back", new_pensum_path  %>)

app/views/subjects/index.html.erb
<h1>Listing subjects of a pensum</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Credits</th>
    <th>Capacity</th>
    <th>Number of Blocks</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.code %></td>
    <td><%= subject.name %></td>
    <td><%= subject.credits %></td>
    <td><%= subject.capacity %></td>
    <td><%= subject.blocks %></td>
    <td><%= link_to 'Show', subject %></td>
    <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
    <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>Pensum</h1>
<p>
  <b>Magister:</b>
  <%= Magister.find(@pensum.magister_id).code %>
</p>
<p>
  <b>Semester:</b>
  <%= @pensum.year %> - <%= @pensum.semester %>
</p>




<h2>Subjects</h2>
   <table>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Credits</th>   
      <th>Capacity</th>    
      <th>Presential hours</th>   
      <th>Enrolled</th> 
    </tr>
  
  <% for subject in Pensum.find(params[:id]).subjects %>
  <% pens = Pensum.find(params[:id]) %>
    <tr>
  
      <td><%= subject.code %></td>
      <td><%= subject.name %></td>
      <td><%= subject.credits %></td>
      <td><%= subject.capacity %></td>
      <td><%= subject.blocks %></td>
      
       
      <% preins = Preinscription.where("pensum_id = ? AND subject_id = ?", subject.pensum_id, subject.code).first %>
      <%if preins !=nil %>
      <td><%= preins.enrolled %></td>
       <%else%>
      <td> 0 </td>
    <%end%>
      <td>
      <td><%= link_to 'Show', subject %></td>
      <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
      <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>

<script>
  function toggle()
  {
    var ns = document.getElementById("newSubject");
    if (ns.hidden)
      ns.hidden = ''
    else
      ns.hidden = 'hidden'
  }
</script>

<a href="javascript:toggle();"><h2>Add subject</h2></a>
<div id='newSubject' hidden>
<%= form_for @subject, :url => {:action => :create, :id => @pensum.id} do |f| %>

  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.err@preinscriptioors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :credits %><br />
    <%= f.text_field :credits %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.text_field :capacity %>
  </div>
  <div class="field">
    <%= f.label "Presential hours" %><br />
    <%= f.text_field :blocks %>
  </div>
  <%= hidden_field_tag(:id, params[:id])%>
 
  <div class="actions">
    <%= f.submit %>    
  </div>
    <%m = Date.current().month%>
    <%if m <= 6%>
      <%= hidden_field_tag(:date, Date.current().year.to_s + '-1')%>
    <%else%>
      <%= hidden_field_tag(:date, Date.current().year.to_s + '-2')%>
    <%end%>
    <%= hidden_field_tag(:enrolled, "0")%>
<% end %>
</div>

<h2>Manage the pensum schedule</h2>
<%= link_to(image_tag("http://www.ellipsistech.com/NSS8_files/icon_lesson_timer.gif"), :controller => :sections, :action => :new, :id => @pensum.id )%>

<br>
<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"), pensums_path)%>





    
    

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @subject.code %>
</p>

<p>
  <b>Name:</b>
  <%= @subject.name %>
</p>

<p>
  <b>Credits:</b>
  <%= @subject.credits %>
</p>

<p>
  <b>Credits:</b>
  <%= @subject.capacity %>
</p>
<p>
  <b>Number of blocks:</b>
  <%= @subject.blocks %>
</p>


<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"),  "new?id="+ @subject.pensum_id.to_s) %>