config/routes.rb
Cr2::Application.routes.draw do

  resources :preinscriptions

  resources :sections

  get "home/index"

  resources :pensums

  resources :subjects

  resources :magisters

  resources :folders


  # The priority is based upon ordeoppan gangnam styler of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
    # match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
 root :to => 'home#index'
  resources :sections do
    collection do
      post :try
    end
  end

  resources :folders do
    collection do
      post :add
    end
  end

  resources :folders do
    collection do
      post :increase
    end
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/pensum.rb
 class Pensum < ActiveRecord::Base
  attr_accessible :magister_id, :semester, :year
  has_many :subjects
  has_many :folders
  has_many :sections
  has_many :preinscriptions
  belongs_to :magister


  #Validar todos los campos requeridos
  validates :year, :semester, :presence => {:message => "Todos los campos son requeridos" }
  
  #Validar asociaciones -> No validar del otro lado (eg de materium a carpetum)
  #  validates_associated :subjects
  validates_associated :folders
  
  #Validar tamaño y tipos
  validates :year, :length => { :is => 4 }
  validates :year, :numericality => { :only_integer => true }
  validates :year, :numericality => { :greater_than => 1970 }
  validates :semester, :length => { :is => 1 }
  validates :semester, :numericality => { :only_integer => true }
  validates :semester, :numericality => { :greater_than_or_equal_to => 0 }
  validates :semester, :numericality => { :less_than_or_equal_to => 2 }

  #Solo se tienen los pensums activos por eso solo puede haber un pensum por maestria
  validates :magister_id, :uniqueness => true
  has_many :schedule

 
  
end

app/controllers/pensums_controller.rb
class PensumsController < ApplicationController
  # GET /pensums
  # GET /pensums.json
  def index
    @pensums = Pensum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pensums }
    end
  end

  # GET /pensums/1
  # GET /pensums/1.json
  def show
    @pensum = Pensum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pensum }
    end
  end

  # GET /pensums/new
  # GET /pensums/new.json
  def new
    @pensum = Pensum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pensum }
    end
  end

  # GET /pensums/1/edit
  def edit
    @pensum = Pensum.find(params[:id])
  end

  # POST /pensums
  # POST /pensums.json
  def create
    @pensum = Pensum.new(params[:pensum])

    respond_to do |format|
      if @pensum.save
        format.html { redirect_to @pensum, notice: 'Pensum was successfully created.' }
        format.json { render json: @pensum, status: :created, location: @pensum }
      else
        format.html { render action: "new" }
        format.json { render json: @pensum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pensums/1
  # PUT /pensums/1.json
  def update
    @pensum = Pensum.find(params[:id])

    respond_to do |format|
      if @pensum.update_attributes(params[:pensum])
        format.html { redirect_to @pensum, notice: 'Pensum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pensum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pensums/1
  # DELETE /pensums/1.json
  def destroy
    @pensum = Pensum.find(params[:id])
    @pensum.destroy

    respond_to do |format|
      format.html { redirect_to pensums_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/pensums_helper.rb
module PensumsHelper
end

app/views/pensums/_form.html.erb
<%= form_for(@pensum) do |f| %>
  <% if @pensum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pensum.errors.count, "error") %> prohibited this pensum from being saved:</h2>

      <ul>
      <% @pensum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :semester %><br />
    <%= f.number_field :semester %>
  </div>
  <div class="field">
    
    <%= f.label :magister %><br />
    <%= f.collection_select :magister_id, Magister.all, :id, :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pensums/edit.html.erb
<h1>Editing pensum</h1>

<%= render 'form' %>

    <td><%= link_to 'Show', :controller => :subjects, :action => :new, :id => @pensum.id %></td>
<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"), pensums_path )%>

app/views/pensums/index.html.erb
<h1>Pensums</h1>

<table>
  <tr>
    <th>Start year</th>
    <th>Semester</th>
    <th>Magister</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pensums.each do |pensum| %>
  <tr>
    <td><%= pensum.year %></td>
    <td><%= pensum.semester %></td>
    <td><%= Magister.find(pensum.magister_id).code %></td>
    <td><%= link_to 'Show', :controller => :subjects, :action => :new, :id => pensum.id %></tdpen>
    <td><%= link_to 'Edit', edit_pensum_path(pensum) %></td>
    <td><%= link_to 'Delete', pensum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pensum', new_pensum_path %> |
<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"),"http://localhost:3000") %>

app/views/pensums/new.html.erb
<h1>New pensum</h1>
<%= render 'form' %>

<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"), pensums_path )%>

app/views/pensums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @pensum.year %>
</p>
<p>
  <b>Magister:</b>
  <%= Magister.find(@pensum.magister_id).code %>
</p>
<p>
  <b>Semester:</b>
  <%= @pensum.semester %>
</p>


<%= link_to 'Edit', edit_pensum_path(@pensum) %> | 
<%= link_to(image_tag("http://www.aquiles.com.ve/images/back_icon_blue.gif"),pensums_path) %>